name: Build Android APK

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PORT: 3000   # 🔥 الحل هنا

    defaults:
      run:
        working-directory: artifacts/satellite-dish-aligner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build web app
        run: pnpm build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: artifacts/satellite-dish-aligner/android/app/build/outputs/apk/debug/*.apk